spring:
    datasource:
        url: jdbc:mysql://172.17.0.2:3306/db_example
        username: springuser
        password: ThePassword
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 8080
